package com.chat.models;

import lombok.Data;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

/**
 * MongoDB document representing a chat message exchanged between two users.
 *
 */
@Data
@Document(collection = "messages")
public class Message {

    /** Unique identifier, auto-generated by MongoDB. */
    @Id
    private String id;

    /** ID of the user who sent the message. */
    private String from;

    /** ID of the user who received the message. */
    private String to;

    /** Text content of the message. */
    private String message;

    /** Timestamp when the document was first persisted. Auto-populated by MongoDB auditing. */
    @CreatedDate
    private Instant createdAt;

    /** Timestamp when the document was last updated. Auto-populated by MongoDB auditing. */
    @LastModifiedDate
    private Instant updatedAt;
}
