package com.chat.models;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * MongoDB document representing a registered chat user.
 */
@Data
@Document(collection = "users")
public class User {

    /** Unique identifier, auto-generated by MongoDB. */
    @Id
    private String id;

    /** Display name of the user. */
    private String name;

    /** Unique email address used for authentication. */
    @Indexed(unique = true)
    private String email;

    /** BCrypt-hashed password. Never returned in API responses. */
    private String password;

    /** Whether the user currently has an active socket connection. */
    private boolean online = false;
}
